/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Mostafa Edrees
 * @brief          : test the drivers of STM32F103C8T6
 * @board          : STM32F103C8T6
 * @processor      : ARM Cortex M3
 ******************************************************************************
 **/
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//-----------------------------
//Includes
//-----------------------------
#include "STM32F103x8.h"

#include "STM32F103x8_GPIO_Driver.h"
#include "STM32F103x8_EXTI_Driver.h"

#include "LCD.h"
#include "Keypad.h"


void Clock_Init(void);

void Toggle_Led(void);

int main(void)
{
	Clock_Init();
	LCD_INIT();

	EXTI_Configuration_t EXTI_CONGIG;
	EXTI_CONGIG.EXTI_PIN = EXTI9PB9;
	EXTI_CONGIG.EXTI_Trigger_Case = EXTI_Trigger_FALLING;
	EXTI_CONGIG.EXTI_IRQ_EN = EXTI_IRQ_ENABLE;
	EXTI_CONGIG.PF_IRQ_CallBack = Toggle_Led;
	MCAL_EXTI_GPIO_Init(&EXTI_CONGIG);


	/* Loop forever */
	while(1)
	{

	}
}

void Toggle_Led(void)
{
	LCD_WRITE_STRING("Interrupt is happened --|__ (FE)");
}

void Clock_Init()
{
	//open clock of AFIO
	RCC_AFIO_CLK_EN();

	//open clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//open clock of GPIOB
	RCC_GPIOB_CLK_EN();
}
