/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Mostafa Edrees
 * @brief          : Lab1 on ARM Modes for Lesson2 on Unit14 (Mastering ARM Cortex-M3/4)
 * @date           : 14/2/2024
 * @board          : STM32F103C8T6
 * @processor      : ARM Cortex M3
 ******************************************************************************
 **/

/*
 * Lab6: Read the Control register and save the value in C variable
 * 		 while CPU in Thread Mode
 */

#include "STM32F103x8.h"
#include "STM32F103x8_GPIO_Driver.h"
#include "STM32F103x8_EXTI_Driver.h"

char IRQ_Flag = 0;

void EXTI9_CallBack(void)
{
	IRQ_Flag = 1;
}

int CPU_Control_Reg_Val = 0;
int Control_Reg_Init_Val = 3;		//This will make us use PSP & Unprivileged

int main(void)
{
	RCC_AFIO_CLK_EN();
	RCC_GPIOB_CLK_EN();

	EXTI_Configuration_t EXTI_config;
	EXTI_config.EXTI_PIN = EXTI9PB9;
	EXTI_config.EXTI_Trigger_Case = EXTI_Trigger_RISING;
	EXTI_config.PF_IRQ_CallBack = EXTI9_CallBack;
	EXTI_config.EXTI_IRQ_EN = EXTI_IRQ_ENABLE;
	MCAL_EXTI_GPIO_Init(&EXTI_config);

	__asm("nop \n\t"
			"nop");

	//1st we will save 3 at Control register then we will read this value
	//write 3 on control register
	__asm("MSR CONTROL, %[IN]"
			:										// 1st : used for output parameters
			:	[IN] "r" (Control_Reg_Init_Val)		// 2nd : used for input parameters
			);

	//read value of control register
	__asm("MRS %[OUT], CONTROL"
			:	[OUT] "=r" (CPU_Control_Reg_Val)	// 1st : used for output parameters
			:										// 2nd : used for input parameters
			: "r3"									// 3rd : used for reserved registers
			);


	__asm("nop \n\t"
			"nop");

	/* Loop forever */
	while(1)
	{
		if(IRQ_Flag)
		{
			IRQ_Flag = 0;
		}
		else
		{

		}
	}
}
