/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Platform_types.h"

//Base address of RCC(reset and clock control) & GPIO_PortA
#define RCC_Base 				0x40021000
#define GPIO_PortA_Base 		0x40010800

//RCC Registers
/*
 * Register Name: Clock control register (RCC_CR)
 * Address offset: 0x00
 * Reset value: 0x0000 XX83
 */
#define RCC_RC					*((vusint32_t *)(RCC_Base + 0x00))
/*
 * Bit 24: PLLON
 * Register: RCC_RC
 * Usage: it is used to enable PLL clock
 * 0 >> PLL OFF
 * 1 >> PLL ON
 * */
#define RCC_RC_PLLON			24

/*
 * Register Name: Clock configuration register (RCC_CFGR)
 * Address offset: 0x04
 * Reset value: 0x0000 0000
 */
#define RCC_CFGR				*((vusint32_t *)(RCC_Base + 0x04))

/*
 * Register Name:  APB2 peripheral clock enable register (RCC_APB2ENR)
 * Address offset: 0x18
 * Reset value: 0x0000 0000
 */
#define RCC_APB2ENR 			*((vusint32_t *)(RCC_Base + 0x18))
/*
 * Bit 2: IOPAEN
 * Register: RCC_APB2ENR
 * Usage: it is used to enable clock of PortA
 * 0 >>  IO port A clock disabled
 * 1 >>  IO port A clock enabled
 * */
#define RCC_APB2ENR_IOPAEN		2


#define PortA_CRH 				*((vusint32_t *)(GPIO_PortA_Base + 0x04))

// union to implement all pins of ODR register
typedef union
{
	usint32_t all_pins;
	struct
	{
		usint32_t reserved:13;
		usint32_t toggle_led:1;
	}Pins;
}R_PortA_ODR_t;
volatile R_PortA_ODR_t *R_ODR = (volatile R_PortA_ODR_t *)(GPIO_PortA_Base + 0x0C);

//Macros to set & clear specific bit
#define SET_BIT(Register,Bit_Num)		Register |= (1 << Bit_Num)
#define CLEAR_BIT(Register,Bit_Num)		Register &= (~(1 << Bit_Num))

void Clock_Init();

int main(void)
{
	Clock_Init();

	//change mode of bits from 20 to 24 to make PortA pin13 is output pin
	PortA_CRH &= 0xFF0FFFFF;
	PortA_CRH |= 0x00200000;

	while(1)
	{
		//toggle led on pin13
		R_ODR->Pins.toggle_led = 1;				//turn on the led
		for(int i = 0; i < 5000; i++);     		//delay
		R_ODR->Pins.toggle_led = 0;				//turn off the led
		for(int i = 0; i < 5000; i++);			//delay
	}

    /* Loop forever */
	for(;;);
}

void Clock_Init()
{
	/*
	 * Bits 1:0 SW: System clock switch
	 * Usage: it is used to select SYSCLK source.
	 * 00: HSI selected as system clock
	 * 01: HSE selected as system clock
	 * 10: PLL selected as system clock
	 * 11: not allowed
	 */
	RCC_CFGR |= (0b10 << 0);

	/*
	 * Bits 21:18 PLLMUL: PLL multiplication factor
	 * Usage: it is used to multiply PLL clock by gain.
	 * Caution: The PLL output frequency must not exceed 72 MHz.
	 * 0000: PLL input clock x 2
	 * 0001: PLL input clock x 3
	 * 0010: PLL input clock x 4
	 * 0011: PLL input clock x 5
	 * 0100: PLL input clock x 6
	 * 0101: PLL input clock x 7
	 * 0110: PLL input clock x 8
	 * 0111: PLL input clock x 9
	 * 1000: PLL input clock x 10
	 * 1001: PLL input clock x 11
	 * 1010: PLL input clock x 12
	 * 1011: PLL input clock x 13
	 * 1100: PLL input clock x 14
	 * 1101: PLL input clock x 15
	 * 1110: PLL input clock x 16
	 * 1111: PLL input clock x 16
	*/
	RCC_CFGR |= (0b0110 << 18);    //4*8 = 32MHz

	/*
	 * Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	 * Usage: it is used to divide SYSCLK by prescaler to get APB1 frequency
	 * 0xx: HCLK not divided
	 * 100: HCLK divided by 2
	 * 101: HCLK divided by 4
	 * 110: HCLK divided by 8
	 * 111: HCLK divided by 16
	 */
	RCC_CFGR |= (0b100 << 8);		//32/2 = 16MHz

	/*
	 * Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	 * Usage: it is used to divide SYSCLK by prescaler to get APB2 frequency
	 * 0xx: HCLK not divided
	 * 100: HCLK divided by 2
	 * 101: HCLK divided by 4
	 * 110: HCLK divided by 8
	 * 111: HCLK divided by 16
	 */
	RCC_CFGR |= (0b101 << 11);		//32/4 = 8MHz

	//enable PLL clock
	SET_BIT(RCC_RC,RCC_RC_PLLON);

	//set pin2 in APB2ENR to enable clock of PortA
	SET_BIT(RCC_APB2ENR,RCC_APB2ENR_IOPAEN);
}
