/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//-----------------------------
//Includes
//-----------------------------
#include "STM32F103x8.h"
#include "STM32F103x8_GPIO_Driver.h"


void Clock_Init(void);
void GPIO_Init(void);
void __delay__(uint32_t x);

int main(void)
{
	Clock_Init();
	GPIO_Init();

	/* Loop forever */
	while(1)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET); //single press
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);	//multi press
		}

		__delay__(1);
	}
}

void Clock_Init()
{
	//open clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//open clock of GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_Init()
{
	GPIO_PIN_Configuration_t *pin_config = NULL;

	//PA1: (Mode >> Input mode(00)) (CNF >>  Floating input(01))
	pin_config->GPIO_PinNumber = GPIO_PIN_1;
	pin_config->GPIO_PinMODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, pin_config);

	//PA13: (Mode >> Input mode(00)) (CNF >>  Floating input(01))
	pin_config->GPIO_PinNumber = GPIO_PIN_13;
	pin_config->GPIO_PinMODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, pin_config);

	//PB1: (Mode >> Output mode, max speed 10 MHz(01)) (CNF >> General purpose output push-pull(00))
	pin_config->GPIO_PinNumber = GPIO_PIN_1;
	pin_config->GPIO_PinMODE = GPIO_MODE_OUTPUT_PP;
	pin_config->GPIO_PinSPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, pin_config);

	//Pin13: (Mode >> Output mode, max speed 10 MHz(01)) (CNF >> General purpose output push-pull(00))
	pin_config->GPIO_PinNumber = GPIO_PIN_13;
	pin_config->GPIO_PinMODE = GPIO_MODE_OUTPUT_PP;
	pin_config->GPIO_PinSPEED = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, pin_config);
}

void __delay__(uint32_t x)
{
	uint32_t i, j;

	for(i = 0; i < x; i++)
		for(j = 0; j < 255; j++);
}
